src/Entity/Usuario.php
<?php
// src/Entity/Usuario.php

namespace App\Entity;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\UserInterface;
use Doctrine\Common\Collections\ArrayCollection;
// =======================================================
// La clase debe implementar UserInterface y Serializable
// =======================================================

/**
 * @ORM\Entity @ORM\Table(name="usuarios")
 */
class Usuario implements UserInterface, \Serializable 
{
	// =======================================================
	// Atributos privados
	// =======================================================

    /**
     * @ORM\Id
     * @ORM\Column(type="string")
     */
    private $usuario;
    /**
     * @ORM\Column(type="string")
     */
    private $clave;
    /**
     * @ORM\Column(type="integer")
     */
    private $rol;
    /**
     * @ORM\Column(type="string")
     */
    private $email;	
    /**
     * @ORM\Column(type="string")
     */
    private $recupera;
	 /**
     * @ORM\Column(type="string")
     */
    private $claveact;
    /**
     * @ORM\Column(type="integer")
     */
    private $activado;
    /**
     * @ORM\Column(type="integer")
     */
    private $edad;
	 /**
     * @ORM\Column(type="string")
     */
    private $ciudad;
	 /**
     * @ORM\Column(type="string")
     */
    private $aficiones;
	 /**
     * @ORM\Column(type="string")
     */
    private $avatar;
    /**
     * @ORM\Column(type="integer")
     */
    private $bloqueo;
	
	/**
     * Un usuario recibe muchos mensajes
     * @ORM\OneToMany(targetEntity="Mensaje", mappedBy="id_destinatario")
     */
	private $recibidos;

	public function getRecibidos()
    {
        return $this->recibidos;

    }


	/**
     * Un usuario envia muchos mensajes
     * @ORM\OneToMany(targetEntity="Mensaje", mappedBy="id_remitente")
     */
	private $enviados;
	public function __construct() {
        $this->recibidos = new ArrayCollection();
        $this->enviados = new ArrayCollection();
    }	
	
	public function getEnviados()
    {
        return $this->enviados;

    }
	// =======================================================
	// Setters y getters
	// =======================================================
    public function getUsuario() {
        return $this->usuario;
    }
    public function setUsuario($usuario) {
       $this->usuario = $usuario;
    }
    public function getClave() {
        return $this->clave;
    }
    public function setClave($clave) {
        $this->clave = $clave;
    }
	public function getRol() {
        return $this->rol;
    }
    public function setRol($rol) {
        $this->rol = $rol;
    }
 	public function getEmail() {
        return $this->email;
    }
    public function setEmail($email) {
        $this->email = $email;
    }
  	public function getRecupera() {
        return $this->recupera;
    }
    public function setRecupera($recupera) {
        $this->recupera = $recupera;
    }
  	public function getClaveact() {
        return $this->claveact;
    }
    public function setClaveact($claveact) {
        $this->claveact = $claveact;
    }
  	public function getActivado() {
        return $this->activado;
    }
    public function setActivado($activado) {
        $this->activado = $activado;
    }
	public function getEdad() {
        return $this->edad;
    }
    public function setEdad($edad) {
        $this->edad = $edad;
    }
	public function getCiudad() {
        return $this->ciudad;
    }
    public function setCiudad($ciudad) {
        $this->ciudad = $ciudad;
    }
	public function getAficiones() {
        return $this->aficiones;
    }
    public function setAficiones($aficiones) {
        $this->aficiones = $aficiones;
    }
	public function getAvatar() {
        return $this->avatar;
    }
    public function setAvatar($avatar) {
        $this->avatar = $avatar;
    }
	public function getBloqueo() {
        return $this->bloqueo;
    }
    public function setBloqueo($bloqueo) {
        $this->bloqueo = $bloqueo;
    }
	
	
 	// =======================================================
	// Elementos necesarios para la autenticación
	// =======================================================
   public function getRoles()
    {
		// Si el usuario es supervisor, entonces tiene acceso
		// a la zona de administración.
	   if($this->bloqueo){		
			return array('ROLE_BLOQUEADO');  
		}
		if($this->rol==true && $this->activado==true){
			return array('ROLE_USER', 'ROLE_ADMIN'); 
		} else if($this->activado){
					
			return array('ROLE_USER');  
		}
		  return array();  
	}

    public function getPassword()
    {
        return $this->getClave();
    }

    public function getSalt()
    {
        return;
    }

    public function getUsername()
    {
        return $this->getUsuario();
    }

    public function eraseCredentials()
    {
        return;
    }
	
	public function serialize(){
        return serialize(array(
            $this->usuario,
            $this->clave,
            $this->rol,
			$this->email,
			$this->recupera,
            $this->claveact,
            $this->activado,
            $this->edad,
			$this->ciudad,
			$this->aficiones,
			$this->avatar,
			$this->bloqueo
        ));
    }
	
    public function unserialize($serialized){
        list (
            $this->usuario,
            $this->clave,
            $this->rol,
			$this->email,
			$this->recupera,
            $this->claveact,
            $this->activado,
            $this->edad,
			$this->ciudad,
			$this->aficiones,
			$this->avatar,
			$this->bloqueo
            ) = unserialize($serialized);
    }
}

templates/acceso.html.twig
{# templates/login.html.twig #}
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title>WhatsChat!</title>
    </head>
    <body>		
		<h2>Bienvenido a WhatsChat!!!</h2>
		{% if mensaje is defined %}
		<br/>{{ mensaje }}
		{% endif %}
		<hr>
    	<form action="{{ path('controlador_login') }}" method="post">
			<br>
			Usuario:
			<input type="text" name="_username" />
			<br>
			Clave
			<input type="password" name="_password" />
			<br>
			<button type="submit">login</button>
		</form>
		
		<br/>
		<td style=><a href={{path('registro')}}>¡Regístrate! </a></td></br>
		<td style=><a href={{path('recuperacionclave')}}>¿Has olvidado tu contraseña? </a></td>
		
    </body>
</html>

templates/administracion.html.twig
{% include 'cabecera.html.twig' %}

	{% block javascripts %}
        <script src="{{ asset('funciones.js') }}" type="text/javascript"></script>
    {% endblock %}
<title>Zona de administración</title>
<h1>
Zona de administracion
</h1>
<table>
<tr><td>Foto de perfil</td><td>Nombre</td><td>Edad</td><td>Aficiones</td><td>Bloqueo</td></tr>
{% for usuario in usuarios %}
<tr><td><img src="uploads/{{usuario.avatar}}" width="80" height="80"></td><td>{{ usuario.usuario }}</td><td>{{ usuario.edad }}</td><td>{{ usuario.aficiones }}</td>
{% if usuario.bloqueo %}
<td><button onclick = "bloquear('{{usuario.usuario}}',0);">DESBLOQUEAR</button></td>
{% else %}
<td><button onclick = "bloquear('{{usuario.usuario}}',1);">BLOQUEAR</button></td>
{% endif %}
</tr>
{% endfor %}
</table>

templates/bandejaEntrada.html.twig
<head>



	
	{% block javascripts %}
        <script src="{{ asset('funciones.js') }}" type="text/javascript"></script>
    {% endblock %}
		<title>Bandeja de entrada</title>
		<meta charset = "UTF-8">
		<script type = "text/javascript" src = "funciones.js"></script>		
	</head>	
{% include 'cabecera.html.twig' %}
{% if 'ROLE_BLOQUEADO' in app.user.roles %}
Contacta con el administrador
{% else %}
	<body>		
	<h1>Bandeja de entrada</h1>
	<table>
	<tr><td>Remitente</td><td>Mensaje</td><td>Fecha</td></tr>
 	{% for mensaje in app.user.recibidos|reverse %}
	
		{% if mensaje.borrado_entrada == false  %}
		{% if mensaje.leido == false  %}
   			<tr style='background-color:yellow' id={{mensaje.id}}><td>{{ mensaje.remitente.usuario }}</td><td>	
			{{ mensaje.mensaje|length > 15 ? mensaje.mensaje|slice(0, 10) ~ '...' : mensaje.mensaje  }}</td><td>{{ mensaje.fecha }}</td>
			<td><button onclick = "return ver_mensaje({{mensaje.id}});">Ver mensaje </button>
			<td><button onclick = "return borrar_mensaje({{mensaje.id}});">Eliminar mensaje </button>
			<td><button onclick = "this.disabled =true; insertar_mensaje('{{mensaje.remitente.usuario}}','{{mensaje.destinatario.usuario}}','{{mensaje.id}}');"  >Responder </button>

		{% else %}
		   <tr  id='{{mensaje.id}}'><td>{{ mensaje.remitente.usuario }}</td><td>
		   {{ mensaje.mensaje|length > 15 ? mensaje.mensaje|slice(0, 10) ~ '...' : mensaje.mensaje  }}			   
		   </td><td>{{ mensaje.fecha }}</td>
		   <td style=><button onclick = "return ver_mensaje({{mensaje.id}});">Ver mensaje </button>
			<td><button onclick = "return borrar_mensaje({{mensaje.id}});">Eliminar mensaje </button>
			<td><button onclick = "this.disabled =true; insertar_mensaje('{{mensaje.remitente.usuario}}','{{mensaje.destinatario.usuario}}','{{mensaje.id}}');"  >Responder </button>
		{% endif %}		
		{% endif %}
    {% endfor %}
	</table>
		<section id = "principal"></section><br>
		{% endif %}
	</body>
</html>

templates/bandejaEntrada_backup.html.twig
{% include 'cabecera.html.twig' %}

{#
<h1>
Usuario {{ app.user.usuario }} <br>
Clave: {{ app.user.clave }} <br>
¿email?: {{ app.user.email }} <br>
¿rol?: {{ app.user.rol }} <br>
recu trueofalse: {{ app.user.recupera }} <br>
claveactivacion {{ app.user.claveact }} <br>
activado trueofalse: {{ app.user.activado }} <br>
edad {{ app.user.edad }} <br>
ciudad {{ app.user.ciudad }} <br>
aficiones {{ app.user.aficiones }} <br>
avatar{{ app.user.avatar }} <br>
bloqueo {{ app.user.bloqueo }} <br>
Mensajes recibidos 
 {% for mensaje in app.user.recibidos %}
        <li>{{ mensaje.mensaje }}</li>
        <li>{{ mensaje.fecha }}</li>
    {% endfor %}
</h1>
#}
<html>
	<title>Bandeja de entrada</title>
	<body>
	<h1>Bandeja de entrada</h1>
	<table>
 	{% for mensaje in app.user.recibidos %}
	
		{% if mensaje.borrado_entrada == false  %}
		{% if mensaje.leido == false  %}
   			<tr><td style='background-color:yellow'>{{ mensaje.remitente.usuario }}</td><td style='background-color:yellow'>	
			{{ mensaje.mensaje|length > 15 ? mensaje.mensaje|slice(0, 10) ~ '...' : mensaje.mensaje  }}</td><td style='background-color:yellow'>{{ mensaje.fecha }}</td>
			<td style=><a href={{path('ver_mensaje' , {'id': mensaje.id})}}>Ver mensaje </a>
			<td style=><a href={{path('eliminar_mensaje' , {'id': mensaje.id})}}>Eliminar mensaje </a></td>

		{% else %}
		   <tr><td>{{ mensaje.remitente.usuario }}</td><td>
		   {{ mensaje.mensaje|length > 15 ? mensaje.mensaje|slice(0, 10) ~ '...' : mensaje.mensaje  }}			   
		   </td><td>{{ mensaje.fecha }}</td>
		   <td style=><a href={{path('ver_mensaje' , {'id': mensaje.id})}}>Ver mensaje </a>
		   <td style=><a href={{path('eliminar_mensaje' , {'id': mensaje.id})}}>Eliminar mensaje </a></td>
		{% endif %}		
		{% endif %}
    {% endfor %}
	</table>
	
	</body>
</html>

templates/bandejaSalida.html.twig
{#
<h1>
Usuario {{ app.user.usuario }} <br>
Clave: {{ app.user.clave }} <br>
¿email?: {{ app.user.email }} <br>
¿rol?: {{ app.user.rol }} <br>
recu trueofalse: {{ app.user.recupera }} <br>
claveactivacion {{ app.user.claveact }} <br>
activado trueofalse: {{ app.user.activado }} <br>
edad {{ app.user.edad }} <br>
ciudad {{ app.user.ciudad }} <br>
aficiones {{ app.user.aficiones }} <br>
avatar{{ app.user.avatar }} <br>
bloqueo {{ app.user.bloqueo }} <br>
Mensajes recibidos 
 {% for mensaje in app.user.recibidos %}
        <li>{{ mensaje.mensaje }}</li>
        <li>{{ mensaje.fecha }}</li>
    {% endfor %}
</h1>
#}
<html>
	<title>Bandeja de Salida</title>
	{% block javascripts %}
        <script src="{{ asset('funciones.js') }}" type="text/javascript"></script>
    {% endblock %}
		<title>Bandeja de salida</title>
		<meta charset = "UTF-8">
		<script type = "text/javascript" src = "funciones.js"></script>		
	</head>	
{% include 'cabecera.html.twig' %}
{% if 'ROLE_BLOQUEADO' in app.user.roles %}
Contacta con el administrador
{% else %}
	<body>		
	<h1>Bandeja de salida</h1>
	<table>
	<tr><td>Destinatario</td><td>Mensaje</td><td>Fecha</td></tr>
 	{% for mensaje in app.user.enviados|reverse %}
	
		{% if mensaje.borrado_salida == false  %}
		{% if mensaje.leido == false  %}
   			<tr style='background-color:yellow' id={{mensaje.id}}><td>{{ mensaje.destinatario.usuario }}</td><td>	
			{{ mensaje.mensaje|length > 15 ? mensaje.mensaje|slice(0, 10) ~ '...' : mensaje.mensaje  }}</td><td>{{ mensaje.fecha }}</td>
			<td><button onclick = "return ver_mensaje_salida({{mensaje.id}});">Ver mensaje </button>
			<td><button onclick = "return borrar_mensaje_salida({{mensaje.id}});">Eliminar mensaje </button>

		{% else %}
		   <tr  id='{{mensaje.id}}'><td>{{ mensaje.destinatario.usuario }}</td><td>
		   {{ mensaje.mensaje|length > 15 ? mensaje.mensaje|slice(0, 10) ~ '...' : mensaje.mensaje  }}			   
		   </td><td>{{ mensaje.fecha }}</td>
		   <td style=><button onclick = "return ver_mensaje_salida({{mensaje.id}});">Ver mensaje </button>
			<td><button onclick = "return borrar_mensaje_salida({{mensaje.id}});">Eliminar mensaje </button>
		{% endif %}		
		{% endif %}
    {% endfor %}
	</table>
		<section id = "principal"></section><br>
{% endif %}	
	</body>
</html>

templates/bandejaSalida_backup.html.twig
{% include 'cabecera.html.twig' %}

{#
<h1>
Usuario {{ app.user.usuario }} <br>
Clave: {{ app.user.clave }} <br>
¿email?: {{ app.user.email }} <br>
¿rol?: {{ app.user.rol }} <br>
recu trueofalse: {{ app.user.recupera }} <br>
claveactivacion {{ app.user.claveact }} <br>
activado trueofalse: {{ app.user.activado }} <br>
edad {{ app.user.edad }} <br>
ciudad {{ app.user.ciudad }} <br>
aficiones {{ app.user.aficiones }} <br>
avatar{{ app.user.avatar }} <br>
bloqueo {{ app.user.bloqueo }} <br>
Mensajes recibidos 
 {% for mensaje in app.user.recibidos %}
        <li>{{ mensaje.mensaje }}</li>
        <li>{{ mensaje.fecha }}</li>
    {% endfor %}
</h1>
#}
<html>
	<title>Bandeja de Salida</title>
	<body>
	<h1>Bandeja de Salida</h1>
	<table>
	{% for mensaje in app.user.enviados %}
	
		{% if mensaje.borrado_salida == false  %}
		{% if mensaje.leido == false  %}
   			<tr><td style='background-color:yellow'>{{ mensaje.destinatario.usuario }}</td><td style='background-color:yellow'>	
			{{ mensaje.mensaje|length > 15 ? mensaje.mensaje|slice(0, 10) ~ '...' : mensaje.mensaje  }}</td><td style='background-color:yellow'>{{ mensaje.fecha }}</td>
			<td style=>No leído </a>
			<td style=><a href={{path('ver_mensaje_salida' , {'id': mensaje.id})}}>Ver mensaje </a>
		   <td style=><a href={{path('eliminar_mensaje_salida' , {'id': mensaje.id})}}>Eliminar mensaje </a></td>

		{% else %}
		   <tr><td>{{ mensaje.destinatario.usuario }}</td><td>
		   {{ mensaje.mensaje|length > 15 ? mensaje.mensaje|slice(0, 10) ~ '...' : mensaje.mensaje  }}			   
		   </td><td>{{ mensaje.fecha }}</td>
		   	<td style=>Leído </a>
		   <td style=><a href={{path('ver_mensaje_salida' , {'id': mensaje.id})}}>Ver mensaje </a>
		   <td style=><a href={{path('eliminar_mensaje_salida' , {'id': mensaje.id})}}>Eliminar mensaje </a></td>
		{% endif %}		
		{% endif %}
    {% endfor %}
	</table>
	
	</body>
</html>

templates/confirmaciones.html.twig
<html>
<body>
</br>

{{mensaje}}</br>
 <a href={{path('controlador_login')}}>Ir a login </a>


</body>
</html>

templates/formuCambio.html.twig
<h1> Formulario de cambio de contraseña </h1>
{{ form_start(form) }}
{{ form_widget(form) }}
{{ form_end(form) }}

templates/formuHola.html.twig
<title>Registro</title>
<h1> Formulario de registro en chat </h1>
{{ form_start(form) }}
{{ form_widget(form) }}
{{ form_end(form) }}
</br>
 <a href={{path('controlador_login')}}>Ir a login </a>

templates/formuMensaje.html.twig
{% include 'cabecera.html.twig' %}
{% if 'ROLE_BLOQUEADO' in app.user.roles %}
Contacta con el administrador
{% else %}
<title>Nuevo mensaje</title>
<h1> Formulario de envío de mensaje {{ app.user.usuario }} </h1>
{{ form_start(form) }}
{{ form_widget(form) }}
{{ form_end(form) }}

{% endif %}

templates/formuPerfil.html.twig
{% include 'cabecera.html.twig' %}

<h1> Bienvenido a tu perfil {{ app.user.usuario }} </h1>

{{ form_start(form) }}
{{ form_widget(form) }}
{{ form_end(form) }}

{% if mensaje is defined %}
    <strong>{{mensaje}}</strong>
{% endif %}

templates/formuRecupera.html.twig
<h1> Formulario de recuperacion de clave </h1>
{{ form_start(form) }}
{{ form_widget(form) }}
{{ form_end(form) }}

</br>
¿Has recordado tu contraseña misteriosamente?</br>
 <a href={{path('controlador_login')}}>Ir a login </a>

templates/mensaje_salida.html.twig
{% include 'cabecera.html.twig' %}

{#
<h1>
Usuario {{ app.user.usuario }} <br>
Clave: {{ app.user.clave }} <br>
¿email?: {{ app.user.email }} <br>
¿rol?: {{ app.user.rol }} <br>
recu trueofalse: {{ app.user.recupera }} <br>
claveactivacion {{ app.user.claveact }} <br>
activado trueofalse: {{ app.user.activado }} <br>
edad {{ app.user.edad }} <br>
ciudad {{ app.user.ciudad }} <br>
aficiones {{ app.user.aficiones }} <br>
avatar{{ app.user.avatar }} <br>
bloqueo {{ app.user.bloqueo }} <br>
Mensajes recibidos 
 {% for mensaje in app.user.recibidos %}
        <li>{{ mensaje.mensaje }}</li>
        <li>{{ mensaje.fecha }}</li>
    {% endfor %}
</h1>
#}
<html>
<body>
<h1>Mensaje de {{ mensaje.remitente.usuario }}</h1>
{{mensaje.mensaje}}
</body>
</html>

templates/ver_users.html.twig
{% include 'cabecera.html.twig' %}

<html>
<body>
{% if 'ROLE_BLOQUEADO' in app.user.roles %}
Contacta con el administrador
{% else %}
<h1>Usuarios en el sistema </h1>

<table>
<tr><td>Foto de perfil</td><td>Nombre</td><td>Edad</td><td>Ciudad</td><td>Aficiones</td></tr>
{% for usuario in usuarios %}
{% if usuario.activado %}
<tr><td><img src="uploads/{{usuario.avatar}}" width="80" height="80"></td><td>{{ usuario.usuario }}</td><td>{{ usuario.edad }}</td><td>{{ usuario.ciudad }}</td><td>{{ usuario.aficiones }}</td></tr>
{% endif %}
{% endfor %}
</table>
{% endif %}
</body>
</html>